### ISSUE TITLE
close ticket onclick cancels the hide and search 

### ISSUE THREAD

**Issue by RoyShnitzel** [ZBejavu/Final2Wix#5]
Steps to reproduce:

search for a ticket/ hide tickets by click
click the close ticket button

**Expected Result:**
The ticket searched/hidden should be displayed

**Actual Result:**
it resets the tickets to default

**Comment by RoyShnitzel** [comment]
also it resets the sort function

**Comment by ZBejavu** [comment]
thanks ! FIXED
